config/routes.rb
Rails.application.routes.draw do
 root "posts#index"
 resources :posts, :authers
end

app/models/auther.rb
class Auther < ActiveRecord::Base
  has_many :posts

  validates :fname, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :auther
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authers_controller.rb
class AuthersController < ApplicationController
  def index
    @authers = Auther.all
  end

  def show
    @auther = Auther.find_by_id(params[:id])
    @auther_post = @auther.posts
  end

  def new
    @auther = Auther.new
  end

  def create
    @auther = Auther.new(auther_params)
    if @auther.save
      flash[:success] = "You have successfully created a new 
      auther!"
      redirect_to authers_path
    else 
      flash[:alert] = "Try again!"
      render :new
    end

  end

  def edit
    @auther = Auther.find_by_id(params[:id]) 
  end

  def update
    @auther = Auther.find_by_id(params[:id])
    if @auther.update_attributes(auther_params)
      flash[:success] = "You have successfully Edited an
      auther!"
      redirect_to authers_path
    else
      flash[:alert] = "Try again!"
      render :edit
    end

  end

  def destroy
    @auther = Auther.find_by_id(params[:id])
    @auther.destroy
  end

  def auther_params
    params.require(:auther).permit(:fname, :lname)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end


  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "You have successfully created a new Post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Enable to create Post please try again!"
      render :new
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "You have successfully updated post!"
      redirect_to posts_path
    else
      flash[:alert] = "Something id wong Try again!"
      render :edit
    end
  end


  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.destroy
      flash[:success] = "You have successfully deleted Post!"
      redirect_to posts_path
    else
      flash[:alert] = "Enable to delete Post please try again!"
      render posts_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :post, :auther_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authers/_form.html.erb
<%= form_for @auther do |f|%>
  <%if @auther.errors.any?%>
    <div class="error_prevantion">
      <h4>
        <%= pluralize(@auther.errors.count,"error")%> prevent you to save
      </h4>
      
      <ul>
        <%@auther.errors.full_messages.each do |error|%>
          <li>
            <%= error%>
          </li>
        <%end%>
      </ul>
    </div>
  <%end%>
    <p>
      <%=f.label :fname%>
      <%=f.text_field :fname%>
    </p>
    <p>
      <%=f.label :lname%>
      <%=f.text_field :lname%>
    </p>

    <p>
      <%=f.submit%>
    </p>

<%end%>

app/views/authers/edit.html.erb
<div class="container">
  <h1>Edit the Auther</h1>
  <%=render 'form'%>
  <%=link_to "Back to Home", authers_path%>
</div>

app/views/authers/index.html.erb
<div class="container">
  <h1>List of all Authers</h1>
  <ul>
    <%@authers.each do |auther|%>
    <li>
      <%=link_to auther.fname, auther_path(auther)%> <%=auther.lname%><br><br>
    </li>
    <%end%>
  </ul>
  <%=button_to "create a new Auther", new_auther_path, method: :get%>
</div>

app/views/authers/new.html.erb
<h1>Create a new Auther</h1>
<%= render 'form'%>
<%=link_to "Back to Home", authers_path%>

app/views/authers/show.html.erb
<div class="container">
    <h1>Detail view</h1>
    <p>
      First Name : <%=@auther.fname%>
    </p>
    <p>
      Last Name : <%=@auther.lname%>
    </p>
    <p>
      Created On : <%=@auther.created_at.to_time%>
    </p>
    <p>
      <ul>
        <%@auther_post.each do |post|%>
          <li>
            <%=post.title%> : <%=post.post%>
          </li>
        <%end%>
      </ul>
    </p>
    <div>
      <%=link_to "Edit", edit_auther_path(params[:id])%> | 
      <%=link_to "Delete", auther_path(params[:id]), method: :delete, data:{confirm:"Are you sure you want to delete the Auther"}%>
    </div><br><br>
    <%=link_to "Back to Home", authers_path%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <ul class="nav">
      <li>
        <a href="<%=posts_path%>">Home</a>
        </li><li>
        <a href="<%=authers_path%>">Authers</a>
        </li><li>
        <a href="#">Contact Me</a>
      </li>
    </ul>
  </nav>
  <div class="sub-body">
  <p class="success">
    <%= flash[:success] if flash[:success]%>
  </p>
  <p class="alert">
    <%= flash[:alert] if flash[:alert]%>
  </p>

<%= yield %>
  </div>
  <footer class="footer">
    <div>
      Copyright @ 2015 web design by Ak & Co.
    </div>
  </footer>
</body>
</html>

app/views/posts/_form.html.erb
<div class="form_block">
<%= form_for @post do |f|%>

  <%if @post.errors.any?%>
    <div class="error_prevantion">
      <h4>
        <%= pluralize(@post.errors.count,"error")%> 
        prevent you to save!
      </h4>
      <ul>
        <%@post.errors.full_messages.each do |error|%>
          <li>
            <%=error%>
          </li>
        <%end%>
      </ul>
    </div>
  <%end%>
    <p>
      <%= f.label :title%>
      <%= f.text_field :title%>
    </p>
    <p>
      <%= f.label :post%>
      <%= f.text_area :post%>
    </p>
    <p>
      <%=f.label :auther_id%>
      <%=f.text_field :auther_id%>
    </p>
    <p>
      <%= f.submit%>
    </p>
<%end%>
</div>

app/views/posts/edit.html.erb
<div class="container">
    <h1>Edit the Post</h1>
    <%=render 'form'%>
    <div>
      <%=link_to "Back to Detail view", post_path(params[:id])%>
    </div><br>
    <div id="back_to_home">
      <%=link_to "Back to Home", posts_path%>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>Post Titles</h1>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <p>
          <%=link_to post.title, post_path(post)%> | 
          <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure you want to delete the Post"}%>
        </p>
      </li>
    <%end%>
  </ul><br><br>
  <p class="link_to_new">
    <%= button_to "Create a new Post", new_post_path, method: :get%>
  </p>
</div>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

  <%= form_for @post do |f|%>
    <p>
      <%= f.label :title%>
      <%= f.text_field :title%>
    </p>
    <p>
      <%= f.label :post%>
      <%= f.text_area :post%>
    </p>
    <p>
      <%= f.submit%>
    </p>
  <%end%>

<div id="back_to_home">
  <%=link_to "Back to Home", posts_path%>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1>Detail of <%=@post.title%></h1>
  <div class="container_post_detail">
    <table class="post_detail">
      <tr>
        <td>Title</td>
        <td>Post</td>
        <td>Created On </td>
        <td>Updated On</td>
        <td>Auther Id</td>
      </tr>
      <tr>
        <td><%=@post.title%></td>
        <td><%=@post.post%></td>
        <td><%=@post.created_at.to_date%></td>
        <td><%=@post.updated_at.to_date%></td>
        <td><%=@post.auther_id%></td>
      </tr>
    </table>
  </div><br>

  <P>
    <%=link_to "Edit", edit_post_path(params[:id])%> | 
    <%=link_to "Delete", post_path(params[:id]), method: :delete, data:{confirm:"Are you sure you want to delete this Post?"}%>
  </P>
  <div id="back_to_home">
    <%=link_to "Back to Home", posts_path%>
  </div>
</div>